### ISSUE TITLE
Pull to refresh?

### ISSUE THREAD

**Issue by Flaque** [RudyB/BulldogBucks#5]
When the user pulls down on the screen, maybe we could have that do the pull to refresh action.

**Comment by RudyB** [comment]
Sounds good to me. Should we remove the refresh button from the bottom menu then?

**Comment by Flaque** [comment]
I think its fine to keep there.

But I'm not sure. Maybe we should test it with folks and see if they can figure out how to refresh without us telling them how to?

**Comment by RudyB** [comment]
I say for now we keep the button as well as the pull to refresh. We could do some A/B testing

**Comment by RudyB** [comment]
Should we use [PullToRefresh](https://github.com/gontovnik/DGElasticPullToRefresh) or [PullToBounce](https://github.com/entotsu/PullToBounce)? 

Also should we remove the current loading animation and replace it with the refresh bar animation?
