### ISSUE TITLE
Show the amount that you can spend per day

### ISSUE THREAD

**Issue by Flaque** [RudyB/BulldogBucks#6]
I showed someone the app and they suggested this. Basically:

amount_left / time_till_end_of_semester = money_per_day

**Comment by RudyB** [comment]
I have a branch that I'm currently working on that does that.

**Comment by Flaque** [comment]
Oh cool :D

**Comment by RudyB** [comment]
Should we count holidays as time until end of semester? Should we account spring break?

**Comment by Flaque** [comment]
oh, this all of a sudden became more complicated than I thought.

But... I would say yes we should count holidays and spring break. It's probably better to error on the side of having a little left over than having none at all.

**Comment by RudyB** [comment]
Good point

**Comment by RudyB** [comment]
How does this look for a mockup? Should we put it here or directly under the "Bulldog Bucks Remaining"?

![mockup](https://cloud.githubusercontent.com/assets/8905028/22571868/85a7a398-e956-11e6-80ed-9224a34b6bc3.png)

**Comment by Flaque** [comment]
I like this a lot.

**Comment by RudyB** [comment]
Should it also be included in the widget?

**Comment by RudyB** [comment]
Should we future proof the app by pulling the the last date of the semester from a backend or do we put it in as a magic number and update the app every semester?

**Comment by Flaque** [comment]
put it in as a magic number at the moment, then work on database. Do the simplest thing first and then work towards a better solution.
